### ISSUE TITLE
Create Search Form Template

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v38-geckos-team-04#29]
**__Task Description__**
Design the Search form template and turn it into the code.

- [x] Design the Search Form
- [x] Create a component file
- [x] Create HTML structure of the template
- [ ] Create style for it in sass
