### ISSUE TITLE
Create the Results List Template

### ISSUE THREAD

**Issue by jaceksupernak** [chingu-voyages/v38-geckos-team-04#30]
**__Task Description__**
Design the Results list template and turn it into the code.

- [x] Design the Search Form
- [x] Create a component file
- [x] Create HTML structure of the template
- [x] Create style for it in sass
